import assert from 'node:assert/strict';
import {selectPilot} from '../research/neural/freeze-pilot.mjs';
const assets=['manufactured','organic','rocks','stress'].flatMap(category=>Array.from({length:7},(_,i)=>({id:`${category}-${i}`,category,split:i===6?'held-out':'development',triangles:i===5?150001:100+i,source_group:`${category}-${i===1?0:i}`})));
const rows=selectPilot({assets},{assets});
assert.equal(rows.length,12);assert.equal(new Set(rows.map(a=>a.source_group)).size,12);
for(const category of ['manufactured','organic','rocks','stress'])assert.deepEqual(rows.filter(a=>a.category===category).map(a=>a.triangles),[100,103,104]);
assert.throws(()=>selectPilot({assets:assets.filter(a=>a.category!=='rocks')},{assets}),/three distinct/);
console.log('Frozen pilot selection contracts passed');
const {residentArguments,persistentLearningCycle}=await import('../research/neural/resident-cycle.mjs');
const args=residentArguments('run',{model:'policy',checkpoint:'optimizer',candidateBatch:2,backend:'fused'});
assert.equal(args[args.indexOf('--duration-minutes')+1],'120');assert.equal(args[args.indexOf('--finalize-minutes')+1],'10');
assert.equal(args[args.indexOf('--vertex-storage')+1],'packed');assert.equal(args[args.indexOf('--update-backend')+1],'fused');
assert.throws(()=>residentArguments('run',{model:'m',checkpoint:'o',minutes:119}),/learning window/);
let executed=false;await assert.rejects(()=>persistentLearningCycle({latest:120*60000,execute(){executed=true;}},{},{now:()=>0}),/no longer fit/);assert.equal(executed,false);
