// Standalone timing view. Concurrent teacher work is shown separately from
// additive learner wall time, so overlap cannot manufacture a speedup.
import fs from 'node:fs';
import path from 'node:path';
import {read} from './runpod-api.mjs';
const [local,remote,output,pipeline,launchStatus]=process.argv.slice(2);
if(!local||!remote||!output)throw new Error('throughput-report.mjs LOCAL_MATRIX REMOTE_MATRIX OUTPUT_HTML [PIPELINE_DIRECTORY] [LAUNCH_STATUS_JSON]');
const launch=launchStatus?read(launchStatus):null;
function rows(file,device){
  const r=read(file);return r.rows.map(row=>{const p=row.report??row,phases=p.phases??[],training=phases.filter(x=>x.phase==='training'),teachers=phases.filter(x=>x.phase==='teacher'),sum=(a,k)=>a.reduce((n,x)=>n+(x[k]??0),0);
    const wall=p.seconds,updates=p.updates_this_invocation??sum(training,'target_step')-sum(training.slice(0,-1),'target_step');
    const result={device,label:row.label??row.variant,complete:p.complete??r.complete,wall,states:p.fresh_states,states_per_second:p.fresh_states_per_second,updates,wait:teachers.reduce((n,t)=>n+(t.learner_wait_seconds??t.wait_seconds??0),0),training:sum(training,'seconds'),optimizer:sum(training,'update_seconds'),capture:sum(training,'capture_seconds'),append:sum(training,'append_seconds'),checkpoint:sum(training,'checkpoint_seconds'),teacher:sum(teachers,'seconds'),teacher_timings:{}};
    for(const t of teachers)for(const [key,value] of Object.entries(t.index?.timings??t.timings??{}))result.teacher_timings[key]=(result.teacher_timings[key]??0)+value;
    result.other=wall-result.wait-result.training;return result;
  });
}
const data=[...rows(local,'RTX 2080 · local shared GPU'),...(remote==='-'?[]:rows(remote,'L40S · remote'))];
function learning(directory){
  if(!directory)return null;const r=read(directory+'/report.json'),p=r.sustained,phases=p.phases,select=name=>phases.filter(x=>x.phase===name),sum=(a,k)=>a.reduce((n,x)=>n+(x[k]??0),0),t=select('training'),teachers=select('teacher');
  const result={ready:r.ready_for_next_training,states:p.fresh_states,updates:p.step,seconds:p.seconds,checkpoint:p.checkpoint_timing,quality:sum(select('quality_audit'),'seconds'),training:sum(t,'seconds'),optimizer:sum(t,'update_seconds'),wait:sum(teachers,'learner_wait_seconds'),teacher:sum(teachers,'seconds'),teacher_timings:{},rows:[],gpu:null};
  for(const a of teachers)for(const [key,value] of Object.entries(a.index?.timings??{}))result.teacher_timings[key]=(result.teacher_timings[key]??0)+value;
  result.other=result.seconds-result.training-result.wait-result.quality;
  const final=select('quality_audit').find(a=>a.profile==='coverage'&&a.ranking==='learned'),initial=r.sustained_initial;
  for(const row of final?.rows??[]){const start=initial?.rows.find(a=>a.asset===row.asset&&a.ranking==='learned'),baseline=select('quality_audit').find(a=>a.profile==='coverage'&&a.ranking==='constant')?.rows.find(a=>a.asset===row.asset);result.rows.push({asset:row.asset,source:row.lods?.[0].triangles,initial:start?.lods?.at(-1).triangles,trained:row.lods?.at(-1).triangles,constant:baseline?.lods?.at(-1).triangles});}
  // GPU timestamps and phase durations come from the same remote clock. The
  // boundaries are approximate at the one-second telemetry sampling interval.
  const telemetry=path.resolve(directory,'../../../gpu-telemetry.csv');
  if(fs.existsSync(telemetry)){let start=r.started;for(const phase of r.phases){if(phase.log==='sustained.log'){const end=start+phase.seconds*1000,a=fs.readFileSync(telemetry,'utf8').trim().split('\n').slice(1).map(line=>{const c=line.split(',').map(s=>s.trim());return {at:Date.parse(c[0].replaceAll('/','-').replace(' ','T')+'Z'),gpu:parseFloat(c[1]),memory:parseFloat(c[3])};}).filter(x=>x.at>=start&&x.at<end&&Number.isFinite(x.gpu));if(a.length)result.gpu={mean:sum(a,'gpu')/a.length,peak:Math.max(...a.map(x=>x.gpu)),memory_mib:Math.max(...a.map(x=>x.memory)),samples:a.length};break;}start+=phase.seconds*1000;}}
  return result;
}
const sustained=learning(pipeline);
const escaped=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=x=>Number.isFinite(x)?x.toFixed(3):'—';
const bar=(name,seconds,total)=>`<li><span>${escaped(name)}</span><b>${number(seconds)} s</b><div class="bar"><i style="width:${Math.max(0,Math.min(100,100*seconds/total))}%"></i></div></li>`;
const overview=s=>s?`<h2>Complete learning cycle · L40S</h2><p><strong>${s.ready||launch?.validation_passed?'Validation gates passed':'Validation remains incomplete'}</strong> · ${s.states.toLocaleString('en')} fresh states · ${s.updates.toLocaleString('en')} optimizer updates · ${number(s.seconds)} s including setup and final audits · ${s.checkpoint.published} verified checkpoints.</p>${s.gpu?`<p>GPU activity averaged ${s.gpu.mean.toFixed(1)}%, peaking at ${s.gpu.peak}%, across ${s.gpu.samples} one-second samples. This measures active time, not the percentage of peak arithmetic throughput. Approximate phase boundaries are used.</p>`:''}<div class="columns"><section><h3>Additive learner wall time</h3><ul>${bar('Wait for audited examples',s.wait,s.seconds)}${bar('Training windows',s.training,s.seconds)}${bar('Final quality audits',s.quality,s.seconds)}${bar('Startup and finalization',s.other,s.seconds)}</ul><p>Optimizer computation inside training windows: ${number(s.optimizer)} s. Checkpoint publication also runs in the background.</p></section><section><h3>Teacher work · overlaps other work</h3><ul>${Object.entries(s.teacher_timings).sort((a,b)=>b[1]-a[1]).map(([k,v])=>bar(k.replaceAll('_',' ').replace(' seconds',''),v,s.teacher)).join('')}</ul></section></div><h3>Coverage diagnostic · final LOD triangle counts</h3><table><thead><tr><th>Mesh</th><th>Source</th><th>Starting policy</th><th>After short training</th><th>Fixed ranking</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${escaped(r.asset)}</td><td>${r.source??'—'}</td><td>${r.initial??'not measured'}</td><td>${r.trained??'—'}</td><td>${r.constant??'—'}</td></tr>`).join('')}</tbody></table><p>These two diagnostic assets use a bounded generation budget and coverage limits. They do not establish generalization, optimal reduction, or preservation of shading. The full validation comparison and incomplete outcomes are retained separately.</p>`:'';
const table=rs=>`<table><thead><tr><th>Configuration</th><th>Wall</th><th>Fresh states/s</th><th>Updates/s · whole cycle</th><th>Learner wait</th><th>Optimizer</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${escaped(r.label)}${r.complete?'':' · incomplete'}</td><td>${number(r.wall)} s</td><td>${number(r.states_per_second)}</td><td>${number(r.updates/r.wall)}</td><td>${number(r.wait)} s</td><td>${number(r.optimizer)} s</td></tr>`).join('')}</tbody></table>`;
const details=r=>`<details><summary>${escaped(r.label)} · ${number(r.states_per_second)} fresh states/s</summary><div class="columns"><section><h3>Learner wall time</h3><ul>${bar('Wait for ordered teacher result',r.wait,r.wall)}${bar('Training window',r.training,r.wall)}${bar('Startup, refresh and finalization',r.other,r.wall)}</ul><h3>Inside training window</h3><ul>${bar('Optimizer updates',r.optimizer,r.training)}${bar('Append / replay tables',r.append,r.training)}${bar('Graph capture',r.capture,r.training)}${bar('Checkpoint submission',r.checkpoint,r.training)}${bar('Other loop work',r.training-r.optimizer-r.append-r.capture-r.checkpoint,r.training)}</ul></section><section><h3>Teacher work · may overlap</h3><ul>${Object.entries(r.teacher_timings).sort((a,b)=>b[1]-a[1]).map(([k,v])=>bar(k.replaceAll('_',' ').replace(' seconds',''),v,r.teacher)).join('')}</ul><p>Teacher work overlaps other teachers and the learner. Do not add these durations to learner wall time.</p></section></div></details>`;
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Blitz concurrent learning timings</title><style>
:root{color-scheme:dark;font-family:system-ui;background:#0b111c;color:#dde9f7}body{max-width:1200px;margin:40px auto;padding:0 24px}h1{font-size:32px}h2{margin-top:42px}p{color:#aebed1;line-height:1.6}.architecture{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:30px 0}.architecture span{padding:14px;border:1px solid #375069;border-radius:8px;background:#152333}.architecture b{color:#59dec3}table{width:100%;border-collapse:collapse;font-variant-numeric:tabular-nums}th,td{padding:12px 10px;text-align:right;border-bottom:1px solid #243649}th:first-child,td:first-child{text-align:left}th{color:#91d8ee}details{margin:12px 0;border:1px solid #293f53;border-radius:8px;padding:14px}summary{cursor:pointer;font-weight:600}.columns{display:grid;grid-template-columns:1fr 1fr;gap:30px}ul{padding:0;list-style:none}li{padding:10px 0}li b{float:right;font-variant-numeric:tabular-nums}.bar{height:6px;background:#203043;margin-top:7px}.bar i{display:block;height:100%;background:#45c1ae}h3{font-size:16px;color:#99c9ef}@media(max-width:700px){.columns{grid-template-columns:1fr}table{font-size:12px}th,td{padding:8px 3px}}
</style><h1>Concurrent learning pipeline</h1>${launch?`<p><strong>Training ${escaped(launch.status)}</strong> · launch preflight passed · ${launch.checkpoint.step.toLocaleString('en')} verified updates and ${launch.checkpoint.fresh_states.toLocaleString('en')} fresh states at ${escaped(launch.captured_at)}. Two-hour learning window ends approximately ${escaped(launch.estimated_learning_end_utc)}. Final training results are pending.</p><p>The launch preflight resolved the remaining model-audit gate in the earlier timing run. Measurements below are from that timing run, not the long training session.</p>`:''}<p>FP32 computation, compact stored meshes and labels. These fixed-work comparisons freeze the teacher policy and verify identical label hashes. Small development meshes measure throughput; they do not establish generalization or release quality.</p><div class="architecture"><span>100 training groups<br>20 validation groups</span><b>→</b><span>Verified packed cache</span><b>→</b><span>1–3 teacher streams<br>Vulkan masks + CUDA audits</span><b>→</b><span>Ordered compact replay</span><b>→</b><span>Captured optimizer graph</span><b>→</b><span>FP64-verified checkpoints<br>60-second cadence</span></div><p>Each teacher wave borrows an immutable policy. Source, trajectory and simplifier seeds are audited against original FP32 geometry. Wider networks are selected only after the separate three-seed quality gate.</p>${overview(sustained)}${[...new Set(data.map(r=>r.device))].map(device=>{const rs=data.filter(r=>r.device===device);return `<h2>${escaped(device)}</h2>${table(rs)}<p>Expand a configuration for timings. Each row requests the same work on this device: ${rs[0]?.states??0} measured fresh states and ${rs[0]?.updates??0} optimizer updates. Compare configurations within a device; the local and remote state budgets differ. Wall includes process setup; CUDA/Vulkan timeline captures are separate instrumented runs.</p>${rs.map(details).join('')}`;}).join('')}<p>No two-hour training session is launched by these validation tools. Incomplete runs retain raw evidence and no aggregate score.</p></html>`;
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,html);fs.writeFileSync(output.replace(/\.html$/,'')+'.json',JSON.stringify({score:null,source:[local,remote,...(pipeline?[pipeline]:[]),...(launchStatus?[launchStatus]:[])],rows:data,sustained,launch},null,2)+'\n');
