// Standalone timing view. Concurrent teacher work is shown separately from
// additive learner wall time, so overlap cannot manufacture a speedup.
import fs from 'node:fs';
import path from 'node:path';
import {read} from './runpod-api.mjs';
const [local,remote,output]=process.argv.slice(2);
if(!local||!remote||!output)throw new Error('throughput-report.mjs LOCAL_MATRIX REMOTE_MATRIX OUTPUT_HTML');
function rows(file,device){
  const r=read(file);return r.rows.map(row=>{const p=row.report??row,phases=p.phases??[],training=phases.filter(x=>x.phase==='training'),teachers=phases.filter(x=>x.phase==='teacher'),sum=(a,k)=>a.reduce((n,x)=>n+(x[k]??0),0);
    const wall=p.seconds,updates=p.updates_this_invocation??sum(training,'target_step')-sum(training.slice(0,-1),'target_step');
    const result={device,label:row.label??row.variant,complete:p.complete??r.complete,wall,states:p.fresh_states,states_per_second:p.fresh_states_per_second,updates,wait:teachers.reduce((n,t)=>n+(t.learner_wait_seconds??t.wait_seconds??0),0),training:sum(training,'seconds'),optimizer:sum(training,'update_seconds'),capture:sum(training,'capture_seconds'),append:sum(training,'append_seconds'),checkpoint:sum(training,'checkpoint_seconds'),teacher:sum(teachers,'seconds'),teacher_timings:{}};
    for(const t of teachers)for(const [key,value] of Object.entries(t.index?.timings??t.timings??{}))result.teacher_timings[key]=(result.teacher_timings[key]??0)+value;
    result.other=wall-result.wait-result.training;return result;
  });
}
const data=[...rows(local,'RTX 2080 · local shared GPU'),...(remote==='-'?[]:rows(remote,'L40S · remote'))];
const escaped=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=x=>Number.isFinite(x)?x.toFixed(3):'—';
const bar=(name,seconds,total)=>`<li><span>${escaped(name)}</span><b>${number(seconds)} s</b><div class="bar"><i style="width:${Math.max(0,Math.min(100,100*seconds/total))}%"></i></div></li>`;
const table=rs=>`<table><thead><tr><th>Configuration</th><th>Wall</th><th>Fresh states/s</th><th>Updates/s · whole cycle</th><th>Learner wait</th><th>Optimizer</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${escaped(r.label)}${r.complete?'':' · incomplete'}</td><td>${number(r.wall)} s</td><td>${number(r.states_per_second)}</td><td>${number(r.updates/r.wall)}</td><td>${number(r.wait)} s</td><td>${number(r.optimizer)} s</td></tr>`).join('')}</tbody></table>`;
const details=r=>`<details><summary>${escaped(r.label)} · ${number(r.states_per_second)} fresh states/s</summary><div class="columns"><section><h3>Learner wall time</h3><ul>${bar('Wait for ordered teacher result',r.wait,r.wall)}${bar('Training window',r.training,r.wall)}${bar('Startup, refresh and finalization',r.other,r.wall)}</ul><h3>Inside training window</h3><ul>${bar('Optimizer updates',r.optimizer,r.training)}${bar('Append / replay tables',r.append,r.training)}${bar('Graph capture',r.capture,r.training)}${bar('Checkpoint submission',r.checkpoint,r.training)}${bar('Other loop work',r.training-r.optimizer-r.append-r.capture-r.checkpoint,r.training)}</ul></section><section><h3>Teacher work · may overlap</h3><ul>${Object.entries(r.teacher_timings).sort((a,b)=>b[1]-a[1]).map(([k,v])=>bar(k.replaceAll('_',' ').replace(' seconds',''),v,r.teacher)).join('')}</ul><p>Teacher work overlaps other teachers and the learner. Do not add these durations to learner wall time.</p></section></div></details>`;
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Blitz concurrent learning timings</title><style>
:root{color-scheme:dark;font-family:system-ui;background:#0b111c;color:#dde9f7}body{max-width:1200px;margin:40px auto;padding:0 24px}h1{font-size:32px}h2{margin-top:42px}p{color:#aebed1;line-height:1.6}.architecture{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:30px 0}.architecture span{padding:14px;border:1px solid #375069;border-radius:8px;background:#152333}.architecture b{color:#59dec3}table{width:100%;border-collapse:collapse;font-variant-numeric:tabular-nums}th,td{padding:12px 10px;text-align:right;border-bottom:1px solid #243649}th:first-child,td:first-child{text-align:left}th{color:#91d8ee}details{margin:12px 0;border:1px solid #293f53;border-radius:8px;padding:14px}summary{cursor:pointer;font-weight:600}.columns{display:grid;grid-template-columns:1fr 1fr;gap:30px}ul{padding:0;list-style:none}li{padding:10px 0}li b{float:right;font-variant-numeric:tabular-nums}.bar{height:6px;background:#203043;margin-top:7px}.bar i{display:block;height:100%;background:#45c1ae}h3{font-size:16px;color:#99c9ef}@media(max-width:700px){.columns{grid-template-columns:1fr}table{font-size:12px}th,td{padding:8px 3px}}
</style><h1>Concurrent learning pipeline</h1><p>FP32 computation, compact stored meshes and labels. These fixed-work comparisons freeze the teacher policy and verify identical label hashes. Small development meshes measure throughput; they do not establish generalization or release quality.</p><div class="architecture"><span>100 training groups<br>20 validation groups</span><b>→</b><span>Verified packed cache</span><b>→</b><span>1–3 teacher streams<br>Vulkan masks + CUDA audits</span><b>→</b><span>Ordered compact replay</span><b>→</b><span>Captured optimizer graph</span><b>→</b><span>FP64-verified checkpoints<br>60-second cadence</span></div><p>Each teacher wave borrows an immutable policy. Source, trajectory and simplifier seeds are audited against original FP32 geometry. Wider networks are selected only after the separate three-seed quality gate.</p>${[...new Set(data.map(r=>r.device))].map(device=>{const rs=data.filter(r=>r.device===device);return `<h2>${escaped(device)}</h2>${table(rs)}<p>Expand a configuration for timings. Each row requests the same work on this device: ${rs[0]?.states??0} measured fresh states and ${rs[0]?.updates??0} optimizer updates. Compare configurations within a device; the local and remote state budgets differ. Wall includes process setup; CUDA/Vulkan timeline captures are separate instrumented runs.</p>${rs.map(details).join('')}`;}).join('')}<p>No two-hour training session is launched by these validation tools. Incomplete runs retain raw evidence and no aggregate score.</p></html>`;
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,html);fs.writeFileSync(output.replace(/\.html$/,'')+'.json',JSON.stringify({score:null,source:[local,remote],rows:data},null,2)+'\n');
