#include "neural_placement_teacher.hpp"
#include "neural_resident_tests.hpp"
#include <c10/cuda/CUDACachingAllocator.h>
#include <csignal>
using namespace blitz;using namespace blitz::neural;using namespace blitz::neural::training;
static volatile std::sig_atomic_t stopped=0;static void stop(int){stopped=1;}
static double seconds(std::chrono::steady_clock::time_point t){return std::chrono::duration<double>(std::chrono::steady_clock::now()-t).count();}
int main(int argc,char** argv){try{
    ieee_fp32();torch::set_num_threads(4);if(!torch::cuda::is_available())return 77;
    if(argc==2&&std::string_view(argv[1])=="--check"){resident_contracts();return 0;}
    if(argc<2)throw std::invalid_argument("blitz-neural-cycle RUN [--passes N] [--states N] [--updates N] [--batch N] [--seed N] [--minutes N] [--initialize MODEL] [--warmstart CHECKPOINT] [--raster-backend cuda|vulkan] [--vertex-storage fp32|position16|packed]");
    fs::path run=argv[1],initialize,warmstart;uint32_t passes=1,states=8,updates=2048,batch=512,seed=101;double minutes=5;bool quality=true,sparse=true;
    NeuralOptions options;options.raster_backend=NeuralRasterBackend::Vulkan;options.memory_mib=2048;
    for(int i=2;i<argc;i+=2){if(i+1==argc)throw std::invalid_argument("missing cycle option");std::string_view key=argv[i];auto* value=argv[i+1];
        if(key=="--passes")passes=neural_unsigned(value);else if(key=="--states")states=neural_unsigned(value);else if(key=="--updates")updates=neural_unsigned(value);else if(key=="--batch")batch=neural_unsigned(value);else if(key=="--seed")seed=neural_unsigned(value);else if(key=="--minutes")minutes=std::stod(value);else if(key=="--initialize")initialize=value;else if(key=="--warmstart")warmstart=value;else if(key=="--raster-backend")options.raster_backend=raster_option(value);else if(key=="--vertex-storage")options.vertex_storage=storage_option(value);else if(key=="--gpu-memory-mib")options.memory_mib=neural_unsigned(value);else if(key=="--quality"){if(std::string_view(value)!="on"&&std::string_view(value)!="off")throw std::invalid_argument("quality must be on or off");quality=std::string_view(value)=="on";}else if(key=="--audit-mode"){if(std::string_view(value)!="sparse"&&std::string_view(value)!="exact")throw std::invalid_argument("audit mode must be sparse or exact");sparse=std::string_view(value)=="sparse";}else throw std::invalid_argument("unknown cycle option");}
    if(!passes||passes>10000||!states||states>64||!updates||updates>100000||!batch||batch>4096||!std::isfinite(minutes)||minutes<=0||minutes>120)throw std::invalid_argument("bounded cycle settings");
    std::signal(SIGINT,stop);std::signal(SIGTERM,stop);fs::create_directories(run/"data");auto begin=std::chrono::steady_clock::now();auto cancelled=[&]{return bool(stopped)||seconds(begin)>=minutes*60;};
    struct Condition{const char* asset;uint32_t pixels,previous;};const std::array conditions={Condition{"ph_painted_wooden_bench",32,0},Condition{"ph_sweet_potato",64,0},Condition{"ph_namaqualand_boulder_04",128,0},Condition{"ph_painted_wooden_bench",128,2},Condition{"ph_sweet_potato",128,2},Condition{"ph_namaqualand_boulder_04",64,2}};
    json contract={{"version",2},{"states",states},{"updates",updates},{"batch",batch},{"seed",seed},{"gpu_memory_mib",options.memory_mib},{"raster",raster_name(options.raster_backend)},{"storage",storage_name(options.draw_storage())},{"sparse",sparse},{"quality",quality},{"initialize",initialize.empty()?"":file_sha256(initialize)},{"warmstart",warmstart.empty()?"":file_sha256(warmstart)},{"training_selection_sha256",file_sha256("research/neural/training-manifest.json")},{"diagnostic_sha256",file_sha256("research/neural/action-diagnostic.json")},{"quality_settings_sha256",file_sha256("research/neural/refactor-smoke.json")},{"binary_sha256",file_sha256("/proc/self/exe")}};
    if(fs::exists(run/"contract.json")&&read_json(run/"contract.json")!=contract)throw std::invalid_argument("persistent cycle contract changed");write_json(run/"contract.json",contract);
    torch::manual_seed(seed);torch::Device device(torch::kCUDA);size_t free_bytes=0,total_bytes=0;cuda_check(cudaMemGetInfo(&free_bytes,&total_bytes));const size_t training_bytes=std::min(size_t(512)<<20,(size_t(options.memory_mib)<<20)/4);c10::cuda::CUDACachingAllocator::setMemoryFraction(double(training_bytes)/total_bytes,0);
    MemoryScope memory(options);memory.budget.limit-=training_bytes;ActionNetwork model(placement_schema);model->to(device);if(!initialize.empty()){auto w=load_weights(initialize);if(w.architecture!=placement_schema)throw std::invalid_argument("cycle requires placement policy");torch::NoGradGuard guard;size_t offset=0;for(auto& p:model->parameters()){p.copy_(torch::from_blob(w.values.data()+offset,p.sizes(),torch::kFloat32));offset+=p.numel();}}
    if(!warmstart.empty())load_checkpoint_model(warmstart,model,device);
    auto initial_policy=run/"initial-model.blzn";if(!fs::exists(run/"latest.json"))save_weights(initial_policy,export_actions(model,{{"seed",seed},{"warmstart",contract.at("warmstart")}}));
    WeightsData initial;initial.architecture=placement_schema;initial.values.resize(policy_weights(placement_schema));ActionCuda policy(initial,options);ResidentDataset data(device,seed);std::unique_ptr<ResidentUpdate> update;CheckpointWriter writer;
    json report={{"complete",false},{"score",nullptr},{"release_quality_proven",false},{"phases",json::array()},{"datasets",json::array()},{"next_condition",0},{"last_audit_iteration",0},{"active_training",nullptr}};uint32_t iteration=0;fs::path checkpoint;
    if(fs::exists(run/"latest.json")){report=read_json(run/"latest.json");iteration=report.at("next_condition");checkpoint=run/report.at("checkpoint").get<std::string>();if(file_sha256(checkpoint/"checkpoint.pt")!=report.at("checkpoint_sha256").get<std::string>())throw std::invalid_argument("cycle checkpoint changed");
        for(auto& name:report.at("datasets")){auto dir=run/"data"/name.get<std::string>();auto index=read_json(dir/"index.json");if(!index.at("complete").get<bool>()||!index.at("reference_confirmed").get<bool>()||index.at("contract_sha256")!=file_sha256(dir/"contract.json")||index.at("sha256")!=file_sha256(dir/"actions.bin"))throw std::invalid_argument("resident recovery shard changed");data.append(load_actions(dir/"actions.bin"),index.at("asset"),index.at("category"));}
        update=std::make_unique<ResidentUpdate>(model,data,batch);load_state(checkpoint/"checkpoint.pt",model,update->optimizer,device);report["complete"]=false;
    }
    auto refresh=[&]{torch::NoGradGuard guard;std::vector<torch::Tensor> parameters;for(auto& p:model->parameters())parameters.push_back(p.flatten());auto weights=torch::cat(parameters);cuda_check(cudaStreamSynchronize(c10::cuda::getCurrentCUDAStream()));policy.refresh_device(weights.data_ptr<float>(),weights.numel());cuda_check(cudaDeviceSynchronize());};refresh();
    double next_audit=1800;auto quality_audit=[&]{if(!quality)return;writer.join();auto manifest=read_json("research/neural/action-diagnostic.json");auto settings=settings_json(read_json("research/neural/refactor-smoke.json"));settings.cancelled=cancelled;
        for(auto ranking:{NeuralRanking::Constant,NeuralRanking::Learned}){auto audit_start=std::chrono::steady_clock::now();auto controls=options;controls.action_trials=8;controls.action_batch=16;controls.ranking=ranking;controls.ranking_seed=101;NeuralModel audit_model((checkpoint/"model.blzn").c_str(),controls);json rows=json::array();
            for(auto& asset:manifest.at("assets")){for(auto& f:asset.at("files"))if(file_sha256(f.at("path").get<std::string>())!=f.at("sha256").get<std::string>())throw std::invalid_argument("diagnostic asset changed");auto mesh=load_mesh(asset.at("path").get<std::string>());NeuralStats stats;auto r=generate_neural(mesh.view(),settings,audit_model,&stats);auto row=result_json(r);row["asset"]=asset.at("id");row["neural"]=neural_json(stats);rows.push_back(row);if(r.status!=Status::Complete)throw std::runtime_error("incomplete hardware quality audit");}
            report["phases"].push_back({{"phase","quality_audit"},{"ranking",ranking_name(ranking)},{"seconds",seconds(audit_start)},{"rows",rows}});}
        report["last_audit_iteration"]=iteration;next_audit=seconds(begin)+1800;
    };
    uint64_t initial_step=update?update->optimizer.state().step:0;
    while(iteration<uint64_t(passes)*conditions.size()&&!cancelled()){
        if(update&&report["active_training"].is_null()&&seconds(begin)>=next_audit)quality_audit();
        auto phase_start=std::chrono::steady_clock::now();
        if(report["active_training"].is_null()){
            const auto& condition=conditions[iteration%conditions.size()];std::string name="shard-"+std::to_string(iteration);
            // A crash before the first durable optimizer snapshot can leave an
            // unreferenced shard. Keep it as evidence and regenerate deterministically.
            auto directory=run/"data"/name;if(fs::exists(directory)){name+="-retry-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count());directory=run/"data"/name;}
            PlacementRequest request;request.states=states;request.pool=4;request.pixels=condition.pixels;request.previous_steps=condition.previous;request.seed=seed+iteration;request.sparse=sparse;request.minutes=std::min(3.,std::max(.001,minutes-seconds(begin)/60));request.cancelled=cancelled;
            request.policy_sha256=file_sha256(checkpoint.empty()?initial_policy:checkpoint/"model.blzn");auto teacher=prepare_placements(condition.asset,directory,request,options,&policy);
            report["phases"].push_back({{"phase","teacher"},{"seconds",seconds(phase_start)},{"index",teacher.index}});if(!teacher.complete)throw std::runtime_error("incomplete teacher shard retained; training skipped");
            phase_start=std::chrono::steady_clock::now();data.append(teacher.data,condition.asset,teacher.index.at("category"));report["datasets"].push_back(name);
            if(!update){update=std::make_unique<ResidentUpdate>(model,data,batch);if(!warmstart.empty()){load_state(warmstart,model,update->optimizer,device);initial_step=update->optimizer.state().step;}}
            update->optimizer.begin_segment();uint32_t target_step=update->optimizer.state().step+updates;if(target_step>1000000)throw std::invalid_argument("optimizer step cap");
            report["active_training"]={{"target_step",target_step},{"append_seconds",seconds(phase_start)},{"capture_seconds",0.},{"update_seconds",0.},{"checkpoint_seconds",0.},{"seconds",0.}};
        }
        auto& progress=report["active_training"];auto capture_start=std::chrono::steady_clock::now();update->capture();progress["capture_seconds"]=progress.at("capture_seconds").get<double>()+seconds(capture_start);uint32_t target_step=progress.at("target_step");
        while(update->optimizer.state().step<target_step&&!cancelled()){
            auto s=update->optimizer.state();auto count=std::min({128u,target_step-s.step,512u-s.step%512});auto t=std::chrono::steady_clock::now();update->run(count);s=update->optimizer.state();progress["update_seconds"]=progress.at("update_seconds").get<double>()+seconds(t);if(s.failure)throw std::runtime_error("nonfinite resident optimizer state");
            if(s.step%512==0||s.step==target_step){t=std::chrono::steady_clock::now();checkpoint=run/"checkpoints"/("step-"+std::to_string(s.step));auto probe=update->input.slice(0,0,std::min<int64_t>(8,batch)).flatten(0,1);torch::NoGradGuard guard;auto expected=model->forward(probe);auto native_input=probe.cpu().contiguous();auto w=export_actions(model,{{"step",s.step}});ActionCuda check_model(w,options,32);auto values=check_model.predict({native_input.data_ptr<float>(),size_t(native_input.numel())});std::vector<double> actual(values.begin(),values.end());if(!legacy_numeric_pass(numeric_difference(doubles(expected),actual)))throw std::runtime_error("resident/native inference parity failed");
                progress["seconds"]=progress.at("seconds").get<double>()+seconds(phase_start);phase_start=std::chrono::steady_clock::now();report["states"]=data.states();
                writer.submit(checkpoint,model,update->optimizer,{{"step",s.step},{"contract",file_sha256(run/"contract.json")}},probe,expected,run/"latest.json",report);progress["checkpoint_seconds"]=progress.at("checkpoint_seconds").get<double>()+seconds(t);}
        }
        writer.join();auto s=update->optimizer.state();if(s.step!=target_step)break;refresh();++iteration;
        auto training=progress;training["seconds"]=training.at("seconds").get<double>()+seconds(phase_start);training["phase"]="training";training["step"]=s.step;training["loss"]=s.loss;training["gradient"]=s.gradient;training["pool"]=update->pool();training["captures"]=update->captures;training["resident_data_bytes"]=data.bytes();report["phases"].push_back(training);report["active_training"]=nullptr;
        report["next_condition"]=iteration;report["step"]=s.step;report["checkpoint"]=fs::relative(checkpoint,run).string();report["checkpoint_sha256"]=file_sha256(checkpoint/"checkpoint.pt");report["states"]=data.states();report["seconds"]=seconds(begin);write_json(run/"latest.json",report);
    }
    writer.join();if(update&&!cancelled()&&report.at("last_audit_iteration").get<uint32_t>()!=iteration)quality_audit();report["complete"]=iteration==uint64_t(passes)*conditions.size()&&!cancelled();report["seconds"]=seconds(begin);report["updates_this_invocation"]=update?update->optimizer.state().step-initial_step:0;
    if(report["complete"].get<bool>())write_json(run/"latest.json",report);write_json(run/"report.json",report);std::cout<<report.dump(2)<<'\n';return report.at("complete").get<bool>()?0:2;
}catch(const std::exception& e){if(argc>1&&std::string_view(argv[1])!="--check"){fs::create_directories(argv[1]);write_json(fs::path(argv[1])/"failure.json",{{"complete",false},{"error",e.what()}});}std::cerr<<"resident cycle: "<<e.what()<<'\n';return 1;}}
