import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const read=async p=>JSON.parse(await fs.readFile(p,'utf8'));
const data=await read('research/vegetation/measurements.json'),lines=['# Vegetation measurements','','Generated by `node tools/vegetation-summary.mjs`. Geometry-only; no foliage SCORE.',''];
const fmt=x=>Number(x).toFixed(3),pct=x=>(100*x).toFixed(1)+'%',modeName=m=>m==='reuse'?'Shared':'Rebuilt';
const run=name=>{const r=data.runs.find(r=>r.name===name);assert.ok(r?.complete,'Incomplete '+name);return r;};
const table=(headers,rows)=>{lines.push('| '+headers.join(' | ')+' |','| '+headers.map(()=>'---').join(' | ')+' |',...rows.map(r=>'| '+r.join(' | ')+' |'),'');};
lines.push('Retention is averaged per category, then equally across categories. Chain excludes LOD0; tail is the last three scheduled slots, including duplicates. Lower is better. Each comparison keeps mode, budget, cohort and pixel contract fixed.','');
const aggregates=[];
for(const cohort of ['matrix','development','validation'])for(const mode of ['reuse','rebuild']){
 const a=run(`vegetation-${cohort}-v3-legacy-${mode}-b8`),b=run(`vegetation-${cohort}-v3-candidate-${mode}-b8`);
 aggregates.push([`${cohort} (${a.expected})`,modeName(mode),`${fmt(a.retention.chain)} → ${fmt(b.retention.chain)}`,`${fmt(a.retention.last_three)} → ${fmt(b.retention.last_three)}`,pct(1-b.retention.last_three/a.retention.last_three),`${fmt(a.retention.final)} → ${fmt(b.retention.final)}`]);
}
table(['Cohort','Vertices','Chain retention','Tail retention','Tail improvement','Final retention'],aggregates);
lines.push('## Fixed-budget quality sweep','','The six-example pilot is development data. Seconds sum generation/search/audit for all six assets, from concurrent shared-workstation runs; they are not isolated speed benchmarks.','');
const quality=[];
for(const mode of ['reuse','rebuild'])for(const budget of [8,32,64])for(const variant of ['legacy','candidate']){
 const r=run(`vegetation-${budget===8?'matrix':'quality'}-v3-${variant}-${mode}-b${budget}`);
 quality.push([modeName(mode),budget,variant,fmt(r.retention.chain),fmt(r.retention.last_three),r.rows.find(a=>a.id==='ph_fern_02_clump_1').triangles.at(-1),r.rows.find(a=>a.id==='loaf_tree_1').triangles.at(-1),r.total_generation_seconds.toFixed(2)]);
}
table(['Vertices','Budget','Variant','Chain','Tail','Fern final tris','Tree final tris','Total bake s'],quality);
lines.push('## External baseline','','Pinned meshoptimizer 1.3; the same eight scheduled levels and geometry gates. These are primary development cases, not a universal ranking. Its UV-aware adapter preserves material partitions and original streams in shared mode.','');
const external=[];
for(const mode of ['reuse','rebuild'])for(const budget of [8,32,64])for(const variant of ['default','prune','permissive-prune']){
 const r=run(`vegetation-meshopt-v1-${variant}-${mode}-b${budget}`);
 external.push([modeName(mode),budget,variant,...['ph_fern_02_clump_1','loaf_tree_1'].map(id=>r.rows.find(r=>r.id===id).triangles.at(-1)),fmt(r.retention.last_three),r.total_generation_seconds.toFixed(2)]);
}
table(['Vertices','Budget','meshoptimizer option','Fern final','Tree final','Mean tail','Total bake s'],external);
lines.push('## Individual regressions at eight proposals','','Every row below worsens at least one of chain, tail or final retention. The grouped aggregate above must not hide these. Ratios compare each mesh to its own source.','');
const regressions=[];
for(const cohort of ['development','validation'])for(const mode of ['reuse','rebuild']){
 const a=run(`vegetation-${cohort}-v3-legacy-${mode}-b8`),b=run(`vegetation-${cohort}-v3-candidate-${mode}-b8`);
 for(const y of b.rows){const x=a.rows.find(x=>x.id===y.id);if(['ratio','tail_ratio','final_ratio'].some(k=>y[k]>x[k]+1e-12))regressions.push([cohort,modeName(mode),y.id,`${fmt(x.ratio)} → ${fmt(y.ratio)}`,`${fmt(x.tail_ratio)} → ${fmt(y.tail_ratio)}`,`${x.triangles.at(-1)} → ${y.triangles.at(-1)}`]);}
}
table(['Cohort','Vertices','Asset','Chain','Tail','Final tris'],regressions);
lines.push('## Independent dense audit','','Last three slots, each against LOD0 and its predecessor. Camera set: 642 orthographic + 64 perspective, seed `0xB1172031`, 8× refined to 32×. Identical render data can short-circuit evaluation, and a failing gate can stop early; 706 is the configured set. No threshold changes or replacement selection use these results.','');
const dense=[];for(const file of (await fs.readdir('research/vegetation/dense')).filter(f=>f.endsWith('.json')).sort()){
 const d=await read('research/vegetation/dense/'+file),failures=[];for(const l of d.lods)for(const gate of ['source','adjacent'])if(!l[gate].passed)failures.push(`L${l.level} ${gate} ${Number(l[gate].error_px).toFixed(2)}/${Number(l[gate==='source'?'source_limit':'transition_limit']).toFixed(2)} px`);
 dense.push([`[${file}](dense/${file})`,d.passed?'PASS':'FAIL',failures.join('; ')||'All six gates passed',pct(Math.max(...d.lods.map(l=>l.source.changed_area)))]);
}
table(['Record','Result','Failed upper error / limit','Worst source area change'],dense);
lines.push('## Opaque pilot compatibility','','Frozen eight-asset, 32→16 px direct pilot. Scores belong only to this opaque pilot. Default replay compares all owned geometry, all attribute streams and LOD measurements against the preserved pre-change executable.','');
const opaque=[];
for(const mode of ['reuse','rebuild']){
 const rows=[];for(const variant of ['baseline','legacy','candidate']){const dir=`research/runs/opaque-vegetation-v3-${variant}-${mode}`,summary=await read(dir+'/summary.json');assert.ok(summary.complete);rows.push(summary);}
 let exact=0;for(const a of (await read('research/pilot.json')).assets){const before=await read(`research/runs/opaque-vegetation-v3-baseline-${mode}/rows/${a.id}.json`),after=await read(`research/runs/opaque-vegetation-v3-legacy-${mode}/rows/${a.id}.json`);assert.ok(before.complete&&!before.failed&&after.complete&&!after.failed);assert.equal(after.output_sha256,before.output_sha256);assert.equal(after.attributes_sha256,before.attributes_sha256);assert.deepEqual(after.result.lods,before.result.lods);++exact;}
 opaque.push([modeName(mode),...rows.map(r=>r.score.toFixed(4)),`${exact}/8 exact`]);
}
table(['Vertices','Old executable SCORE','Unchanged defaults SCORE','Candidate SCORE','Default replay'],opaque);
lines.push('## Timing repeats','','Three new runs with one bake worker and proposal tracing disabled. Other work on the shared workstation was not controlled. The geometry hashes must agree with each other and the six-example matrix. This includes generation/search/audit, excludes import/export.','');
const timings=[];
for(const variant of ['legacy','candidate'])for(const mode of ['reuse','rebuild'])for(const id of ['ph_fern_02_clump_1','loaf_tree_1']){
 const samples=[],reference=await read(`research/runs/vegetation-matrix-v3-${variant}-${mode}-b8/rows/${id}.json`);
 for(let r=1;r<=3;r++){const row=await read(`research/runs/vegetation-timing-v3-r${r}-${variant}-${mode}-b8/rows/${id}.json`);assert.ok(row.complete&&!row.failed);assert.equal(row.output_sha256,reference.output_sha256);samples.push(row.generation_seconds);}
 const sorted=samples.slice().sort((a,b)=>a-b);timings.push([id,modeName(mode),variant,...samples.map(s=>s.toFixed(2)),sorted[1].toFixed(2),`${sorted[0].toFixed(2)}–${sorted[2].toFixed(2)}`]);
}
table(['Asset','Vertices','Variant','Run 1 s','Run 2 s','Run 3 s','Median s','Range s'],timings);
lines.push('## Geometry rendering proxies','','Final LOD at 16 px over the fixed 16 acceptance views. Quads are counted per primitive before depth; these are CPU geometry diagnostics, not alpha-tested texture overdraw or GPU timings. Changed area is the maximum symmetric difference divided by union across the bake audit views.','');
const costs=[];
for(const mode of ['reuse','rebuild'])for(const variant of ['legacy','candidate']){
 const report=await read(`research/vegetation/cost/${variant}-${mode}.json`);assert.ok(report.diagnostics_complete);
 for(const asset of report.assets){const l=asset.lods.at(-1),c=l.render_cost;costs.push([asset.id,modeName(mode),variant,l.triangles,pct(c.fraction_under_one_px2),c.primitive_quads,fmt(c.quad_lane_utilization),fmt(c.pre_depth_overlap),pct(l.source.changed_area)]);}
}
table(['Asset','Vertices','Variant','Tris','Under 1 px²','Primitive quads','Lane utilization','Pre-depth overlap','Changed area'],costs);
lines.push('Raw per-asset results, proposal rejections, stage times, peak RSS and input/build hashes are in [measurements.json](measurements.json) and the linked run folders under `research/runs/`. Historical v1/v2 prototypes retain their original measurements; they are not merged with the final v3 contract.','');
await fs.writeFile('research/vegetation/RESULTS.md',lines.join('\n'));
console.log(`Wrote ${aggregates.length} grouped comparisons, ${dense.length} dense audits, ${regressions.length} regression rows.`);
