if(BLITZ_ACQUISITION)
  find_package(CURL REQUIRED)
  find_package(LibArchive REQUIRED)
  add_executable(blitz-corpus tools/acquisition/corpus.cpp tools/acquisition/acquisition.cpp tools/acquisition/neural_corpus.cpp)
  if(NOT BLITZ_CUDA)
    target_sources(blitz-corpus PRIVATE src/neural/model_io.cpp)
  endif()
  add_library(blitz_foliage_tools STATIC tools/foliage.cpp)
  target_include_directories(blitz_foliage_tools PRIVATE third_party)
  target_link_libraries(blitz_foliage_tools PUBLIC nlohmann_json::nlohmann_json PRIVATE blitz_io CURL::libcurl OpenSSL::Crypto LibArchive::LibArchive)
  if(MSVC)
    target_compile_options(blitz_foliage_tools PRIVATE /fp:strict)
  else()
    target_compile_options(blitz_foliage_tools PRIVATE -ffp-contract=off -fno-fast-math)
  endif()
  target_include_directories(blitz-corpus PRIVATE src .)
  target_link_libraries(blitz-corpus PRIVATE blitz_io blitz_foliage_tools CURL::libcurl OpenSSL::Crypto LibArchive::LibArchive)
endif()
