# Opt-in via CMAKE_PROJECT_INCLUDE. Also works with the frozen baseline without
# changing its source tree. Only Ninja scheduling and an aggregate target change.
include_guard(GLOBAL)
if(NOT CMAKE_GENERATOR STREQUAL "Ninja")
  message(FATAL_ERROR "Cloud build scheduling requires Ninja")
endif()
foreach(variable BLITZ_CLOUD_JOBS BLITZ_CLOUD_CUDA_JOBS)
  if(NOT "${${variable}}" MATCHES "^[1-8]$")
    message(FATAL_ERROR "${variable} must be an integer in [1,8]")
  endif()
endforeach()
if(BLITZ_CLOUD_CUDA_JOBS GREATER 2 OR BLITZ_CLOUD_CUDA_JOBS GREATER BLITZ_CLOUD_JOBS)
  message(FATAL_ERROR "Cloud CUDA pool must not exceed two or the global job limit")
endif()
set_property(GLOBAL APPEND PROPERTY JOB_POOLS blitz_cloud_cuda=${BLITZ_CLOUD_CUDA_JOBS} blitz_cloud_heavy=1 blitz_cloud_link=1)

function(blitz_cloud_build_targets)
  get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
  set(heavy_targets blitz_neural_training blitz-neural-train blitz-neural-replay blitz-neural-action-train blitz-neural-cycle blitz-neural-diagnostics blitz-neural-placement-prepare)
  set(manifest "{\n  \"version\": 1,\n  \"jobs\": ${BLITZ_CLOUD_JOBS},\n  \"cuda_jobs\": ${BLITZ_CLOUD_CUDA_JOBS},\n  \"heavy_jobs\": 1,\n  \"compile_pools\": {")
  set(separator "")
  foreach(target IN LISTS targets)
    get_target_property(type ${target} TYPE)
    if(NOT type MATCHES "^(EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY|OBJECT_LIBRARY|MODULE_LIBRARY)$")
      continue()
    endif()
    set(pool "default")
    if(target IN_LIST heavy_targets)
      set(pool blitz_cloud_heavy)
    else()
      get_target_property(sources ${target} SOURCES)
      foreach(source IN LISTS sources)
        if(source MATCHES "\\.cu$")
          set(pool blitz_cloud_cuda)
        endif()
      endforeach()
    endif()
    if(NOT pool STREQUAL "default")
      set_property(TARGET ${target} PROPERTY JOB_POOL_COMPILE ${pool})
    endif()
    set_property(TARGET ${target} PROPERTY JOB_POOL_LINK blitz_cloud_link)
    string(APPEND manifest "${separator}\n    \"${target}\": \"${pool}\"")
    set(separator ",")
  endforeach()
  string(APPEND manifest "\n  },\n  \"validation_targets\": [")
  if(TARGET blitz-test-executables)
    get_property(validation_targets TARGET blitz-test-executables PROPERTY BLITZ_NATIVE_TEST_TARGETS)
    foreach(target blitz-neural-placement-prepare blitz-neural-cycle blitz-neural-diagnostics)
      if(TARGET ${target})
        list(APPEND validation_targets ${target})
      endif()
    endforeach()
    list(REMOVE_DUPLICATES validation_targets)
    list(SORT validation_targets)
    add_custom_target(blitz-neural-cloud-validation DEPENDS ${validation_targets})
    set(separator "")
    foreach(target IN LISTS validation_targets)
      string(APPEND manifest "${separator}\n    \"${target}\"")
      set(separator ",")
    endforeach()
  endif()
  string(APPEND manifest "\n  ]\n}\n")
  file(WRITE "${CMAKE_BINARY_DIR}/cloud-build-targets.json" "${manifest}")
endfunction()
cmake_language(DEFER CALL blitz_cloud_build_targets)
