if(BLITZ_NEURAL_TOOLS)
  add_executable(blitz-neural-prepare tools/neural/prepare.cpp)
  target_include_directories(blitz-neural-prepare PRIVATE src .)
  target_link_libraries(blitz-neural-prepare PRIVATE blitz_io)
  add_executable(blitz-neural-action-prepare tools/neural/action_prepare.cpp)
  target_include_directories(blitz-neural-action-prepare PRIVATE src .)
  target_link_libraries(blitz-neural-action-prepare PRIVATE blitz_io)
  add_executable(blitz-neural-placement-prepare tools/neural/placement_prepare.cpp)
  target_include_directories(blitz-neural-placement-prepare PRIVATE src .)
  # The shared teacher uses native CUDA state and audit streams.
  # Declare its toolkit dependency; a development shell's include path is not
  # available to an ordinary C++ compiler in the deployment container.
  target_link_libraries(blitz-neural-placement-prepare PRIVATE blitz_io CUDA::cudart CUDA::cublas)
  add_executable(blitz-neural-profile tools/neural/profile.cpp)
  target_include_directories(blitz-neural-profile PRIVATE src .)
  target_link_libraries(blitz-neural-profile PRIVATE blitz_io CUDA::cudart)
  add_executable(blitz-neural-edt-profile tools/neural/edt_profile.cu)
  target_include_directories(blitz-neural-edt-profile PRIVATE src .)
  target_link_libraries(blitz-neural-edt-profile PRIVATE blitzremesher nlohmann_json::nlohmann_json CUDA::cudart CUDA::nppif CUDA::nppc)
  set_target_properties(blitz-neural-edt-profile PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED ON)
  add_executable(blitz-neural-precision-profile tools/neural/precision_profile.cpp)
  target_include_directories(blitz-neural-precision-profile PRIVATE src .)
  target_link_libraries(blitz-neural-precision-profile PRIVATE blitz_io CUDA::cudart)
  if(BLITZ_VULKAN)
    add_executable(blitz-neural-packing-diagnostic tools/neural/packing_diagnostic.cpp)
    add_executable(blitz-neural-pilot-prepare tools/neural/pilot_prepare.cpp)
    target_include_directories(blitz-neural-pilot-prepare PRIVATE src .)
    target_link_libraries(blitz-neural-pilot-prepare PRIVATE blitz_io CUDA::cudart CUDA::cublas OpenSSL::Crypto)
    target_include_directories(blitz-neural-packing-diagnostic PRIVATE . src)
    target_link_libraries(blitz-neural-packing-diagnostic PRIVATE blitz_io)
    add_executable(blitz-neural-hardware-profile tools/neural/hardware_profile.cpp)
    target_include_directories(blitz-neural-hardware-profile PRIVATE src .)
    target_link_libraries(blitz-neural-hardware-profile PRIVATE blitz_io CUDA::cudart)
  endif()
  add_executable(blitz-neural-action-proof tools/neural/action_proof.cpp)
  target_include_directories(blitz-neural-action-proof PRIVATE src .)
  target_link_libraries(blitz-neural-action-proof PRIVATE blitz_io)
endif()
