if(BLITZ_CUDA)
  if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
    set(CMAKE_CUDA_ARCHITECTURES 75 CACHE STRING "CUDA architectures for neural kernels")
  endif()
  enable_language(CUDA)
  find_package(CUDAToolkit 12 REQUIRED)
  find_package(OpenSSL REQUIRED)
  target_sources(blitzremesher PRIVATE src/neural/model_io.cpp src/neural/inference.cu src/neural/evaluate.cu src/neural/action_gpu.cu src/neural/quantization.cpp)
  target_compile_definitions(blitzremesher PRIVATE BLITZ_CUDA)
  target_link_libraries(blitzremesher PRIVATE CUDA::cudart CUDA::cublas OpenSSL::Crypto)
  set_target_properties(blitzremesher PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED ON)
  target_compile_options(blitzremesher PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--fmad=false;--prec-div=true;--prec-sqrt=true>)
endif()
if(BLITZ_VULKAN)
  if(NOT BLITZ_CUDA)
    message(FATAL_ERROR "BLITZ_VULKAN requires BLITZ_CUDA")
  endif()
  find_package(Vulkan REQUIRED COMPONENTS glslangValidator)
  file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/shaders")
  foreach(shader neural_raster_vert neural_coverage_vert neural_raster_frag neural_coverage_frag)
    if(shader MATCHES "_vert$")
      set(shader_source src/neural/shaders/neural_raster.vert)
      set(shader_flags)
      if(shader STREQUAL "neural_coverage_vert")
        set(shader_flags -DCOVERAGE=1)
      endif()
    else()
      set(shader_source src/neural/shaders/neural_raster.frag)
      set(shader_flags)
      if(shader STREQUAL "neural_coverage_frag")
        set(shader_flags -DCOVERAGE=1)
      endif()
    endif()
    set(shader_output "${CMAKE_CURRENT_BINARY_DIR}/shaders/${shader}.inc")
    add_custom_command(OUTPUT "${shader_output}"
      COMMAND Vulkan::glslangValidator -V --target-env vulkan1.3 ${shader_flags} --vn ${shader} -o "${shader_output}" "${CMAKE_CURRENT_SOURCE_DIR}/${shader_source}"
      DEPENDS "${shader_source}" VERBATIM)
    target_sources(blitzremesher PRIVATE "${shader_output}")
  endforeach()
  target_sources(blitzremesher PRIVATE src/neural/vulkan.cpp src/neural/vulkan_cuda.cu)
  target_include_directories(blitzremesher PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/shaders")
  target_compile_definitions(blitzremesher PRIVATE BLITZ_VULKAN)
  target_link_libraries(blitzremesher PRIVATE Vulkan::Vulkan CUDA::nppif CUDA::nppc)
endif()
if(BLITZ_NEURAL_TRAIN AND NOT BLITZ_CUDA)
  message(FATAL_ERROR "BLITZ_NEURAL_TRAIN requires BLITZ_CUDA")
endif()
