if(BUILD_TESTING)
  get_property(blitz_targets_before_tests DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
  # CPU-only tests exercise the optional model format without linking CUDA.
  if(NOT BLITZ_CUDA)
    find_package(OpenSSL REQUIRED)
    add_library(blitz-neural-model-test-support STATIC src/neural/model_io.cpp)
    target_include_directories(blitz-neural-model-test-support PRIVATE src include)
    target_link_libraries(blitz-neural-model-test-support PRIVATE OpenSSL::Crypto)
    set(blitz_model_test_support blitz-neural-model-test-support)
  endif()
  find_package(Threads REQUIRED)
  add_executable(blitz-neural-worker-retirement-tests tests/neural_worker_retirement.cpp)
  target_include_directories(blitz-neural-worker-retirement-tests PRIVATE . src)
  target_compile_features(blitz-neural-worker-retirement-tests PRIVATE cxx_std_20)
  target_link_libraries(blitz-neural-worker-retirement-tests PRIVATE Threads::Threads)
  add_test(NAME neural-worker-retirement-contracts COMMAND blitz-neural-worker-retirement-tests)
  set_tests_properties(neural-worker-retirement-contracts PROPERTIES TIMEOUT 30)
  add_executable(blitz-neural-teacher-cancellation-tests tests/neural_teacher_cancellation.cpp)
  target_include_directories(blitz-neural-teacher-cancellation-tests PRIVATE . src include)
  target_compile_features(blitz-neural-teacher-cancellation-tests PRIVATE cxx_std_20)
  add_test(NAME neural-teacher-cancellation-contracts COMMAND blitz-neural-teacher-cancellation-tests)
  add_executable(blitz-neural-teacher-seed-tests tests/neural_teacher_seed.cpp)
  target_include_directories(blitz-neural-teacher-seed-tests PRIVATE . src include)
  target_compile_features(blitz-neural-teacher-seed-tests PRIVATE cxx_std_20)
  add_test(NAME neural-teacher-seed-contracts COMMAND blitz-neural-teacher-seed-tests)
  add_executable(blitz-neural-teacher-strategy-tests tests/neural_teacher_strategy.cpp)
  target_include_directories(blitz-neural-teacher-strategy-tests PRIVATE .)
  target_compile_features(blitz-neural-teacher-strategy-tests PRIVATE cxx_std_20)
  add_test(NAME neural-teacher-strategy-contracts COMMAND blitz-neural-teacher-strategy-tests)
  add_executable(blitz-neural-chain-tests tests/neural_chain.cpp)
  target_include_directories(blitz-neural-chain-tests PRIVATE src)
  target_link_libraries(blitz-neural-chain-tests PRIVATE blitzremesher)
  add_test(NAME neural-chain-integration-contracts COMMAND blitz-neural-chain-tests)
  add_executable(blitz-shared-vertex-tests tests/shared_vertices.cpp)
  target_link_libraries(blitz-shared-vertex-tests PRIVATE blitzremesher)
  target_include_directories(blitz-shared-vertex-tests PRIVATE src)
  add_test(NAME shared-vertex-contracts COMMAND blitz-shared-vertex-tests)
  add_executable(blitz-wedge-tests tests/wedges.cpp)
  target_link_libraries(blitz-wedge-tests PRIVATE blitzremesher)
  target_include_directories(blitz-wedge-tests PRIVATE src)
  add_test(NAME wedge-contracts COMMAND blitz-wedge-tests)
  add_executable(blitz-density-tests tests/density.cpp)
  target_link_libraries(blitz-density-tests PRIVATE blitzremesher)
  add_test(NAME density-contracts COMMAND blitz-density-tests)
  add_executable(blitz-appearance-tests tests/appearance.cpp)
  target_link_libraries(blitz-appearance-tests PRIVATE blitzremesher)
  target_include_directories(blitz-appearance-tests PRIVATE src)
  add_test(NAME appearance-contracts COMMAND blitz-appearance-tests)
  add_executable(blitz-chain-graph-tests tests/chain_graph.cpp)
  target_link_libraries(blitz-chain-graph-tests PRIVATE blitzremesher)
  add_test(NAME chain-graph-contracts COMMAND blitz-chain-graph-tests)
  add_executable(blitz-neural-reference-tests tests/neural_reference.cpp)
  target_include_directories(blitz-neural-reference-tests PRIVATE src .)
  target_link_libraries(blitz-neural-reference-tests PRIVATE blitzremesher)
  add_test(NAME neural-reference-contracts COMMAND blitz-neural-reference-tests)
  add_executable(blitz-neural-model-scope-tests tests/neural_model_scope.cpp)
  target_include_directories(blitz-neural-model-scope-tests PRIVATE src .)
  target_link_libraries(blitz-neural-model-scope-tests PRIVATE blitzremesher ${blitz_model_test_support})
  add_test(NAME neural-model-scope-contracts COMMAND blitz-neural-model-scope-tests)
  add_executable(blitz-neural-vertex-storage-tests tests/neural_vertex_storage.cpp)
  target_include_directories(blitz-neural-vertex-storage-tests PRIVATE src .)
  target_link_libraries(blitz-neural-vertex-storage-tests PRIVATE blitzremesher)
  add_test(NAME neural-vertex-storage-contracts COMMAND blitz-neural-vertex-storage-tests)
  if(TARGET blitz_io)
    add_executable(blitz-neural-action-dataset-tests tests/neural_action_dataset.cpp)
    target_include_directories(blitz-neural-action-dataset-tests PRIVATE . src)
    target_link_libraries(blitz-neural-action-dataset-tests PRIVATE blitz_io ${blitz_model_test_support})
    add_test(NAME neural-action-dataset-contracts COMMAND blitz-neural-action-dataset-tests)
    add_executable(blitz-neural-rollout-outcome-tests tests/neural_rollout_outcome.cpp)
    target_include_directories(blitz-neural-rollout-outcome-tests PRIVATE . include)
    target_link_libraries(blitz-neural-rollout-outcome-tests PRIVATE nlohmann_json::nlohmann_json)
    add_test(NAME neural-rollout-outcome-contracts COMMAND blitz-neural-rollout-outcome-tests)
    add_executable(blitz-neural-compact-tests tests/neural_compact.cpp)
    target_include_directories(blitz-neural-compact-tests PRIVATE . src)
    target_link_libraries(blitz-neural-compact-tests PRIVATE blitz_io)
    add_test(NAME neural-compact-storage-contracts COMMAND blitz-neural-compact-tests)
  endif()
  if(BLITZ_VULKAN)
    add_executable(blitz-neural-observer-tests tests/neural_observer.cpp)
    target_include_directories(blitz-neural-observer-tests PRIVATE src .)
    target_link_libraries(blitz-neural-observer-tests PRIVATE blitzremesher CUDA::cudart CUDA::cublas)
    add_test(NAME neural-observer-contracts COMMAND blitz-neural-observer-tests)
    set_tests_properties(neural-observer-contracts PROPERTIES SKIP_RETURN_CODE 77)
    add_executable(blitz-neural-vulkan-tests tests/neural_vulkan.cpp)
    target_include_directories(blitz-neural-vulkan-tests PRIVATE src .)
    target_link_libraries(blitz-neural-vulkan-tests PRIVATE blitzremesher CUDA::cudart CUDA::cublas)
    add_test(NAME neural-vulkan-contracts COMMAND blitz-neural-vulkan-tests)
    set_tests_properties(neural-vulkan-contracts PROPERTIES SKIP_RETURN_CODE 77)
  endif()
  if(BLITZ_CUDA AND TARGET blitz_io)
    add_executable(blitz-neural-audit-io-tests tests/neural_audit_io.cpp)
    target_include_directories(blitz-neural-audit-io-tests PRIVATE .)
    target_link_libraries(blitz-neural-audit-io-tests PRIVATE blitz_io OpenSSL::Crypto)
    if(BLITZ_VULKAN)
      target_compile_definitions(blitz-neural-audit-io-tests PRIVATE BLITZ_TEST_VULKAN)
    endif()
    add_test(NAME neural-audit-replay-contracts COMMAND blitz-neural-audit-io-tests)
    set_tests_properties(neural-audit-replay-contracts PROPERTIES SKIP_RETURN_CODE 77)
  endif()
  find_program(BLITZ_NODE_EXECUTABLE node)
  if(BLITZ_NODE_EXECUTABLE)
    add_test(NAME neural-pilot-selection-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_pilot.mjs)
    add_test(NAME neural-runner-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_runner.mjs)
    add_test(NAME neural-cloud-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_cloud.mjs)
    add_test(NAME neural-build-setup-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_build_setup.mjs)
    add_test(NAME neural-action-runner-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_action.mjs)
    add_test(NAME neural-refactor-runner-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_refactor.mjs)
    add_test(NAME neural-corpus-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_corpus.mjs)
    add_test(NAME neural-pipeline-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_pipeline.mjs)
    add_test(NAME neural-teacher-profile-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_teacher_profile.mjs)
    add_test(NAME neural-native-stack-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_native_stack.mjs)
    add_test(NAME neural-width-quality-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_width_quality.mjs)
    add_test(NAME neural-policy-ranking-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_policy_ranking.mjs)
    add_test(NAME neural-teacher-optimization-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_teacher_optimization.mjs)
    add_test(NAME neural-teacher-capability-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_teacher_capability.mjs)
    add_test(NAME neural-baseline-overlay-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_baseline_overlay.mjs)
    add_test(NAME neural-baseline-cache-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_baseline_cache.mjs)
    set_tests_properties(neural-refactor-runner-contracts PROPERTIES WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
    if(TARGET blitz AND BLITZ_CUDA)
      add_test(NAME neural-cli-contracts COMMAND ${BLITZ_NODE_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/neural_cli.mjs $<TARGET_FILE:blitz>)
    endif()
  endif()
  add_executable(blitz-neural-tests tests/neural.cpp)
  target_include_directories(blitz-neural-tests PRIVATE src .)
  target_link_libraries(blitz-neural-tests PRIVATE blitzremesher)
  add_test(NAME neural-contracts COMMAND blitz-neural-tests)
  add_executable(blitz-neural-action-tests tests/neural_action.cpp)
  target_include_directories(blitz-neural-action-tests PRIVATE src .)
  target_link_libraries(blitz-neural-action-tests PRIVATE blitzremesher)
  add_test(NAME neural-action-contracts COMMAND blitz-neural-action-tests)
  if(BLITZ_CUDA)
    add_executable(blitz-neural-predicate-tests tests/neural_predicate.cpp)
    target_include_directories(blitz-neural-predicate-tests PRIVATE src .)
    target_link_libraries(blitz-neural-predicate-tests PRIVATE blitzremesher)
    add_test(NAME neural-predicate-contracts COMMAND blitz-neural-predicate-tests)
    set_tests_properties(neural-predicate-contracts PROPERTIES SKIP_RETURN_CODE 77)
    add_executable(blitz-neural-action-gpu-tests tests/neural_action_gpu.cpp)
    target_include_directories(blitz-neural-action-gpu-tests PRIVATE src .)
    target_link_libraries(blitz-neural-action-gpu-tests PRIVATE blitzremesher CUDA::cudart)
    add_test(NAME neural-action-gpu-contracts COMMAND blitz-neural-action-gpu-tests)
    set_tests_properties(neural-action-gpu-contracts PROPERTIES SKIP_RETURN_CODE 77)
  endif()
  if(BLITZ_CUDA)
    target_compile_definitions(blitz-neural-tests PRIVATE BLITZ_CUDA)
    target_link_libraries(blitz-neural-tests PRIVATE CUDA::cudart)
    add_test(NAME neural-cuda-contracts COMMAND blitz-neural-tests --cuda)
    set_tests_properties(neural-cuda-contracts PROPERTIES SKIP_RETURN_CODE 77)
  endif()
  if(BLITZ_NEURAL_TRAIN)
    add_test(NAME neural-libtorch-cuda-contract COMMAND blitz-neural-train --check-cuda)
    set_tests_properties(neural-libtorch-cuda-contract PROPERTIES SKIP_RETURN_CODE 77)
    add_test(NAME neural-action-libtorch-contract COMMAND blitz-neural-action-train --check)
    set_tests_properties(neural-action-libtorch-contract PROPERTIES SKIP_RETURN_CODE 77)
    add_test(NAME neural-device-update-contracts COMMAND blitz-neural-action-train --check-update)
    set_tests_properties(neural-device-update-contracts PROPERTIES SKIP_RETURN_CODE 77)
    add_test(NAME neural-resident-cycle-contracts COMMAND blitz-neural-diagnostics --check)
    add_test(NAME neural-schema-contracts COMMAND blitz-neural-diagnostics --check-schema)
    set_tests_properties(neural-schema-contracts PROPERTIES SKIP_RETURN_CODE 77)
    add_test(NAME neural-checkpoint-failure-contracts COMMAND blitz-neural-diagnostics --check-checkpoint)
    set_tests_properties(neural-checkpoint-failure-contracts PROPERTIES SKIP_RETURN_CODE 77)
    add_test(NAME neural-checkpoint-cancellation COMMAND blitz-neural-diagnostics --diagnose-checkpoint "${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/neural-cancellation" "${CMAKE_CURRENT_BINARY_DIR}/cancellation-result.json")
    set_tests_properties(neural-resident-cycle-contracts PROPERTIES SKIP_RETURN_CODE 77)
  endif()
  add_executable(blitz-coverage-cache-tests tests/coverage_cache.cpp)
  target_include_directories(blitz-coverage-cache-tests PRIVATE src .)
  target_link_libraries(blitz-coverage-cache-tests PRIVATE blitzremesher)
  add_test(NAME coverage-cache-contracts COMMAND blitz-coverage-cache-tests)
  add_executable(blitz-hybrid-tests tests/hybrid.cpp)
  target_link_libraries(blitz-hybrid-tests PRIVATE blitzremesher)
  add_test(NAME hybrid-contracts COMMAND blitz-hybrid-tests)
  add_executable(blitz-vegetation-tests tests/vegetation.cpp)
  target_include_directories(blitz-vegetation-tests PRIVATE src .)
  target_link_libraries(blitz-vegetation-tests PRIVATE blitzremesher)
  add_test(NAME vegetation-contracts COMMAND blitz-vegetation-tests)
  add_executable(blitz-tests tests/contracts.cpp)
  target_link_libraries(blitz-tests PRIVATE blitzremesher)
  add_test(NAME contracts COMMAND blitz-tests)
  add_executable(blitz-precision-tests tests/precision.cpp)
  target_include_directories(blitz-precision-tests PRIVATE src .)
  target_link_libraries(blitz-precision-tests PRIVATE blitzremesher)
  add_test(NAME precision-contracts COMMAND blitz-precision-tests)
  add_executable(blitz-render-cost-tests tests/render_cost.cpp)
  target_link_libraries(blitz-render-cost-tests PRIVATE blitzremesher)
  add_test(NAME render-cost-contracts COMMAND blitz-render-cost-tests)
  add_executable(blitz-c-smoke tests/c_smoke.c)
  target_link_libraries(blitz-c-smoke PRIVATE blitzremesher)
  set_target_properties(blitz-c-smoke PROPERTIES LINKER_LANGUAGE CXX)
  add_test(NAME c-abi COMMAND blitz-c-smoke)
  if(BLITZ_ACQUISITION)
    add_executable(blitz-foliage-tests tests/foliage.cpp)
    target_link_libraries(blitz-foliage-tests PRIVATE blitz_foliage_tools LibArchive::LibArchive)
    add_test(NAME foliage-contracts COMMAND blitz-foliage-tests)
  endif()
  if(TARGET blitz_io)
    add_executable(blitz-io-tests tests/io_tests.cpp)
    target_include_directories(blitz-io-tests PRIVATE . src)
    target_link_libraries(blitz-io-tests PRIVATE blitz_io)
    add_test(NAME io-contracts COMMAND blitz-io-tests)
  endif()
  # Native fixtures are captured as they are declared, so adding a test target
  # does not silently omit it from the narrower remote build. These tools are
  # referenced by tests but were declared outside this file.
  get_property(blitz_test_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
  list(REMOVE_ITEM blitz_test_targets ${blitz_targets_before_tests})
  foreach(test_tool blitz blitz-neural-train blitz-neural-action-train blitz-neural-diagnostics)
    if(TARGET ${test_tool})
      list(APPEND blitz_test_targets ${test_tool})
    endif()
  endforeach()
  add_custom_target(blitz-test-executables DEPENDS ${blitz_test_targets})
  set_property(TARGET blitz-test-executables PROPERTY BLITZ_NATIVE_TEST_TARGETS "${blitz_test_targets}")
endif()
