if(BLITZ_TOOLS OR BLITZ_NEURAL_TOOLS OR BLITZ_NEURAL_TRAIN OR BLITZ_ACQUISITION)
  find_package(nlohmann_json REQUIRED)
  find_package(OpenSSL REQUIRED)
  add_library(blitz_io src/io.cpp)
  target_include_directories(blitz_io PUBLIC include PRIVATE third_party)
  target_link_libraries(blitz_io PUBLIC blitzremesher nlohmann_json::nlohmann_json)
endif()
if(BLITZ_TOOLS)
  add_executable(blitz-appearance-replay tools/appearance_replay.cpp)
  target_link_libraries(blitz-appearance-replay PRIVATE blitz_io)
  add_executable(blitz-chain-inspect tools/chain_inspect.cpp)
  target_link_libraries(blitz-chain-inspect PRIVATE blitz_io)
  add_executable(blitz tools/main.cpp tools/benchmark.cpp)
  target_include_directories(blitz PRIVATE .)
  target_link_libraries(blitz PRIVATE blitz_io OpenSSL::Crypto)
  add_executable(blitz-microbench tools/microbench.cpp)
  target_link_libraries(blitz-microbench PRIVATE blitzremesher nlohmann_json::nlohmann_json)
  add_executable(blitz-precision-bench tools/precision_bench.cpp)
  target_include_directories(blitz-precision-bench PRIVATE src)
  target_link_libraries(blitz-precision-bench PRIVATE blitzremesher nlohmann_json::nlohmann_json)
  add_executable(blitz-report tools/report.cpp)
  target_link_libraries(blitz-report PRIVATE nlohmann_json::nlohmann_json)
  add_executable(blitz-board tools/board.cpp)
  target_link_libraries(blitz-board PRIVATE nlohmann_json::nlohmann_json OpenSSL::Crypto)
  add_executable(blitz-probe tools/probe.cpp)
  target_link_libraries(blitz-probe PRIVATE blitz_io OpenSSL::Crypto)
  add_executable(blitz-lod-report tools/lod_report.cpp)
  target_link_libraries(blitz-lod-report PRIVATE blitz_io OpenSSL::Crypto)
  add_executable(blitz-tail-audit tools/tail_audit.cpp)
  target_include_directories(blitz-tail-audit PRIVATE src)
  target_link_libraries(blitz-tail-audit PRIVATE blitz_io OpenSSL::Crypto)
endif()
